function genparamtable
for D = [10, 30, 50, 100]
	tablefilename = 'CEC15_PARAM_TABLE.xlsx';
	sheet = sprintf('D=%d', D);
	xlswrite(tablefilename, {...
		sprintf('D = %d', D); ...
		'NPinit - NPmin'; ...
		'Finit'; ...
		'CRinit'; ...
		'ERinit'; ...
		'p'; ...
		'H'; ...
		'Q'; ...
		'w(EXT)'; ...
		'ainit'; ...
		'w(ER)'; ...
		'CRmin'; ...
		'CRmax - CRmin'; ...
		'NPmin'; ...
		'w(CR)'; ...
		'w(F)'; ...
		'Solution Error'}, sheet, 'A1:A17');
	
	xlswrite(tablefilename, {...
		'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', ...
		'f12', 'f13', 'f14', 'f15', 'Default'}, sheet, 'B1:Q1');
	
	for f = 1 : 15
		filename = sprintf('optimize_de_result_D%df%d.mat', D, f);
		load(filename);
		
		col = char('A' + f);
		xlswrite(tablefilename, xmin, sheet, sprintf('%c2:%c16', col, col));
		xlswrite(tablefilename, fmin - f * 100, sheet, sprintf('%c17', col));
	end
	
	filename = sprintf('default_de_D%d.mat', D);
	load(filename);
	
	xlswrite(tablefilename, xmin, sheet, 'Q2:Q16');
	xlswrite(tablefilename, {'-'}, sheet, 'Q17');	
end
end